language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
script:
  - coverage run setup.py test --live

before_install:
  - mkdir -p ${DEST}
  - curl -u ${KEY} ${HOST}/${FILE} > ${DEST}/${FILE}

install:
  - pip install --quiet -r requirements.txt -r test_requirements.txt

after_success:
  - coveralls
