language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip

env:
  - SET="-m logic"
  - SET="-m live"
  - SET="-m destructive"

install:
  - pip install --quiet -r requirements.txt -r test_requirements.txt

before_script:
  - mkdir -p $HOME/$DEST
  - curl -u $KEY $HOST/$FILE > $HOME/$DEST/$FILE

script:
  - coverage run setup.py test --addopts "--profile $SET"

after_success:
  - coveralls

before_deploy:
  - echo "[gist]\ntoken: $GIST" > $HOME/.gist

deploy:
  provider: script
  script: gist create "Travis $TRAVIS_REPO_SLUG $TRAVIS_BUILD_NUMBER $SET" prof/combined.svg
