language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip

env:
  - SET=--logic
  - SET=--live
  - SET=--destructive
script:
  - coverage run setup.py test --addopts $SET

before_install:
  - mkdir -p $HOME/$DEST
  - curl -u $KEY $HOST/$FILE > $HOME/$DEST/$FILE

install:
  - pip install --quiet -r requirements.txt -r test_requirements.txt

after_success:
  - coveralls
